### ISSUE TITLE
Checksums didn't match for dataset source files

### ISSUE THREAD

**Issue by hsb1995** [OpenGVLab/OmniQuant#65]
![image](https://github.com/OpenGVLab/OmniQuant/assets/149936473/857d81f4-ec3e-4134-b9c3-aa9f2fb06eab)
Can the. zst file be provided?

![image](https://github.com/OpenGVLab/OmniQuant/assets/149936473/659eb404-8591-4b38-8898-54b791a9778f)
Unable to match dataset resources at the beginning of downloading the dataset

**Comment by hsb1995** [comment]
Your work has been very fulfilling, and I would like to reproduce it, but the following issues have arisen. I would like to ask for your help in answering.

**Comment by hsb1995** [comment]
![image](https://github.com/OpenGVLab/OmniQuant/assets/149936473/5240cfdf-6460-4ada-ab69-5b727c45b0fd)
![image](https://github.com/OpenGVLab/OmniQuant/assets/149936473/222f408e-9012-4257-815f-b1a469c1c421)
![image](https://github.com/OpenGVLab/OmniQuant/assets/149936473/92a95cc4-47ea-4cb0-bad2-5568b3d534e2)

**Comment by hsb1995** [comment]
![image](https://github.com/OpenGVLab/OmniQuant/assets/149936473/126cb9ca-73aa-4eb9-a7cf-7e363450a2be)
I searched for this issue on Google and their response was that the version of the datasets package is too high (2.18.0), so I tried many methods according to the installation you provided (datasets=2.0.0), but was unsuccessful. Could you please help me take a look.

**Comment by hsb1995** [comment]
Another Google scholar said: pip install git+ https://github.com/huggingface/datasets.git Then set: dataset=load_dataset ("multinews", download_mode="force-redownload"). I changed the ’**datautils**‘ file according to this setting: traindata=load_dataset (path='wikitext ', name='wikitext-2-raw v1', split='train ', download_mode="force-redownload")
Testdata=load_dataset (path='wikitext ', name='wikitext-2-raw v1', split='test ', download_mode="force-redownload")
then the bug is
![image](https://github.com/OpenGVLab/OmniQuant/assets/149936473/2d4c37db-0136-4dc5-84e4-062751561784)
![image](https://github.com/OpenGVLab/OmniQuant/assets/149936473/94a98f2c-2396-4039-95bf-8f5d716f58ce)

I have tried many ways but still haven't solved it. Could you please take some time to take a look

**Comment by hsb1995** [comment]
Oh my goodness, I finally solved the bug. Thank you to the author. I downloaded the dataset and loaded it locally. however
![image](https://github.com/OpenGVLab/OmniQuant/assets/149936473/19e31cd8-0d5d-408d-8948-456eb581cde6)
![image](https://github.com/OpenGVLab/OmniQuant/assets/149936473/e6dd5d71-1e3d-42b2-9890-304bdcd743fe)

**Comment by hsb1995** [comment]
Dear author, I have been researching experiments on quantifying large-scale pre trained models recently and have seen that you have done such a perfect job. I would like to reproduce your code. This error occurred on the way, please help resolve it.

[2024-03-13 21:49:20 root](omniquant.py 50): INFO Starting ...
[2024-03-13 21:49:22 root](omniquant.py 193): INFO === Start quantize layer 0 ===
Traceback (most recent call last):
  File "/home/sam/Doctorproject/OmniQuant-main/main.py", line 382, in <module>
    main()
  File "/home/sam/Doctorproject/OmniQuant-main/main.py", line 352, in main
    omniquant(
  File "/home/sam/Doctorproject/OmniQuant-main/quantize/omniquant.py", line 213, in omniquant
    fp_inps[j] = qlayer(fp_inps[j].unsqueeze(0), attention_mask=attention_mask,position_ids=position_ids)[0]
  File "/home/sam/anaconda3/envs/omniquant/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sam/Doctorproject/OmniQuant-main/models/int_llama_layer.py", line 241, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/sam/anaconda3/envs/omniquant/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sam/Doctorproject/OmniQuant-main/models/int_llama_layer.py", line 124, in forward
    cos, sin = self.rotary_emb(value_states, seq_len=kv_seq_len)
  File "/home/sam/anaconda3/envs/omniquant/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sam/anaconda3/envs/omniquant/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
TypeError: LlamaRotaryEmbedding.forward() missing 1 required positional argument: 'position_ids'

Process finished with exit code 1

**Comment by hsb1995** [comment]
it is done, transformer's version is too high, please set the autuor's provide
![image](https://github.com/OpenGVLab/OmniQuant/assets/149936473/6df9b2f3-036d-40cc-8d25-665527cfeb42)
