### ISSUE TITLE
Which bug do you fix for auto_gptq

### ISSUE THREAD

**Issue by BaohaoLiao** [OpenGVLab/OmniQuant#79]
Hi, I want to use the newest version of auto_gptq. In this repos, you fix some bugs of the original auto_gptq. May I ask what you mainly fix?

In addition, when I set --real_quant. it raises an OutOfResources error as follows during the evaluation after successful packing. I use a A100-80GB and the model is llama-2-7b. Do you know the reason?

```
  0%|                                                                                                                                           | 0/166 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/baliao/.conda/envs/new_omniquant/lib/python3.10/site-packages/auto_gptq/nn_modules/triton_utils/custom_autotune.py", line 74, in _bench
    return triton.testing.do_bench(kernel_call, percentiles=(0.5, 0.2, 0.8), rep=40)
TypeError: do_bench() got an unexpected keyword argument 'percentiles'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/chatgpt/data/baliao/apiq_final/01_blockwise/ApiQ/./apiq/main.py", line 146, in <module>
    main(args)
  File "/data/chatgpt/data/baliao/apiq_final/01_blockwise/ApiQ/./apiq/main.py", line 92, in main
    evaluate(model, tokenizer, args, logging)
  File "/home/baliao/.conda/envs/new_omniquant/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/chatgpt/data/baliao/apiq_final/01_blockwise/ApiQ/apiq/evaluate.py", line 45, in evaluate
    outputs = model.base_model.model.model(batch)
  File "/home/baliao/.conda/envs/new_omniquant/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/baliao/.conda/envs/new_omniquant/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/baliao/.conda/envs/new_omniquant/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 922, in forward
    layer_outputs = decoder_layer(
  File "/home/baliao/.conda/envs/new_omniquant/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/baliao/.conda/envs/new_omniquant/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/baliao/.conda/envs/new_omniquant/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 672, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/baliao/.conda/envs/new_omniquant/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/baliao/.conda/envs/new_omniquant/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/baliao/.conda/envs/new_omniquant/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 366, in forward
    query_states = self.q_proj(hidden_states)
  File "/home/baliao/.conda/envs/new_omniquant/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/baliao/.conda/envs/new_omniquant/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/baliao/.conda/envs/new_omniquant/lib/python3.10/site-packages/peft/tuners/lora/layer.py", line 557, in forward
    result = self.base_layer(x, *args, **kwargs)
  File "/home/baliao/.conda/envs/new_omniquant/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/baliao/.conda/envs/new_omniquant/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/baliao/.conda/envs/new_omniquant/lib/python3.10/site-packages/auto_gptq/nn_modules/qlinear/qlinear_triton.py", line 136, in forward
    out = quant_linear_fn.apply(
  File "/home/baliao/.conda/envs/new_omniquant/lib/python3.10/site-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/baliao/.conda/envs/new_omniquant/lib/python3.10/site-packages/torch/cuda/amp/autocast_mode.py", line 123, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/home/baliao/.conda/envs/new_omniquant/lib/python3.10/site-packages/auto_gptq/nn_modules/triton_utils/kernels.py", line 399, in forward
    output = quant_matmul_248(input, qweight, scales, qzeros, g_idx, bits, maxq)
  File "/home/baliao/.conda/envs/new_omniquant/lib/python3.10/site-packages/auto_gptq/nn_modules/triton_utils/kernels.py", line 323, in quant_matmul_248
    quant_matmul_248_kernel[grid](
  File "/home/baliao/.conda/envs/new_omniquant/lib/python3.10/site-packages/auto_gptq/nn_modules/triton_utils/custom_autotune.py", line 92, in run
    timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
  File "/home/baliao/.conda/envs/new_omniquant/lib/python3.10/site-packages/auto_gptq/nn_modules/triton_utils/custom_autotune.py", line 92, in <dictcomp>
    timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
  File "/home/baliao/.conda/envs/new_omniquant/lib/python3.10/site-packages/auto_gptq/nn_modules/triton_utils/custom_autotune.py", line 75, in _bench
    except triton.compiler.OutOfResources:
AttributeError: module 'triton.compiler' has no attribute 'OutOfResources'
```

**Comment by ChenMnZ** [comment]
Please refer https://github.com/ChenMnZ/AutoGPTQ-bugfix/commit/ad5b0d72eece9a3cf6d4b7a5c710a6cc0331de80 for details.
